/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_diegovarela;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Exam2 extends javax.swing.JFrame {

    private ArrayList<Atm> atms = new ArrayList();
    private ArrayList<cliente> client = new ArrayList();
    private ArrayList<Mantenimiento> manten = new ArrayList();

    /**
     * Creates new form Exam2
     */
    public Exam2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear_atm = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_ubic = new javax.swing.JTextField();
        tf_idatm = new javax.swing.JTextField();
        tf_manetenimiento = new javax.swing.JTextField();
        jd_fabric = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        decision_usuario = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jb_cliente = new javax.swing.JButton();
        jb_mantenimiento = new javax.swing.JButton();
        crear_cliente = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jd_nacius = new com.toedter.calendar.JDateChooser();
        jd_afius = new com.toedter.calendar.JDateChooser();
        tf_idus = new javax.swing.JTextField();
        tf_primus = new javax.swing.JTextField();
        tf_segunus = new javax.swing.JTextField();
        tf_apeus = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tf_segunape = new javax.swing.JTextField();
        tf_contraseñaus = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        crear_mantenimiento = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jd_nacius1 = new com.toedter.calendar.JDateChooser();
        jd_afius1 = new com.toedter.calendar.JDateChooser();
        tf_idus1 = new javax.swing.JTextField();
        tf_primus1 = new javax.swing.JTextField();
        tf_segunus1 = new javax.swing.JTextField();
        tf_apeus1 = new javax.swing.JTextField();
        jb_crearmantenimiento = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        tf_segunape1 = new javax.swing.JTextField();
        cb_elegiratm = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        tf_contraseñaus1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        decidir_atm = new javax.swing.JDialog();
        cb_atms = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jb_aceptar = new javax.swing.JButton();
        decidir_usuario = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        inicio_cliente = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        pf_contraseña = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        inicio_mantenimiento = new javax.swing.JDialog();
        cliente = new javax.swing.JDialog();
        mantenimiento = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jb_crearatm = new javax.swing.JButton();
        jb_crearus = new javax.swing.JButton();
        jb_iniciosesion = new javax.swing.JButton();

        jLabel2.setText("Ubicacion:");

        jLabel3.setText("iD del ATM:");

        jLabel4.setText("Fecha de fabricacion:");

        jLabel5.setText("Mantenimiento:");

        jButton1.setText("Crear ATM");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Crear_atmLayout = new javax.swing.GroupLayout(Crear_atm.getContentPane());
        Crear_atm.getContentPane().setLayout(Crear_atmLayout);
        Crear_atmLayout.setHorizontalGroup(
            Crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_atmLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_atmLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jd_fabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(Crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Crear_atmLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_manetenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                            .addGroup(Crear_atmLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_idatm))
                            .addGroup(Crear_atmLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_ubic)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        Crear_atmLayout.setVerticalGroup(
            Crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_atmLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_ubic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_idatm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jd_fabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(Crear_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_manetenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Que tipo de usuario deseas crear?");

        jb_cliente.setText("Cliente");
        jb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_clienteMouseClicked(evt);
            }
        });

        jb_mantenimiento.setText("Mantenimiento");
        jb_mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_mantenimientoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout decision_usuarioLayout = new javax.swing.GroupLayout(decision_usuario.getContentPane());
        decision_usuario.getContentPane().setLayout(decision_usuarioLayout);
        decision_usuarioLayout.setHorizontalGroup(
            decision_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decision_usuarioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(decision_usuarioLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jb_cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_mantenimiento)
                .addGap(78, 78, 78))
        );
        decision_usuarioLayout.setVerticalGroup(
            decision_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decision_usuarioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(104, 104, 104)
                .addGroup(decision_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cliente)
                    .addComponent(jb_mantenimiento))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jLabel7.setText("Id usuario:");

        jLabel8.setText("Primer nombre:");

        jLabel9.setText("Segundo nombre:");

        jLabel10.setText("Primer apellido:");

        jLabel11.setText("Fecha de nacimineto:");

        jLabel12.setText("Fecha de afiliacion:");

        jButton2.setText("Crear usuario");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel13.setText("Segundo apellido:");

        jLabel26.setText("Contraseña:");

        javax.swing.GroupLayout crear_clienteLayout = new javax.swing.GroupLayout(crear_cliente.getContentPane());
        crear_cliente.getContentPane().setLayout(crear_clienteLayout);
        crear_clienteLayout.setHorizontalGroup(
            crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_clienteLayout.createSequentialGroup()
                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(crear_clienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2)
                                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(crear_clienteLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_idus))
                                    .addGroup(crear_clienteLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_primus))
                                    .addGroup(crear_clienteLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_segunus))
                                    .addGroup(crear_clienteLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_apeus))
                                    .addGroup(crear_clienteLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                        .addComponent(jd_afius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crear_clienteLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_segunape))))
                            .addGroup(crear_clienteLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jd_nacius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(crear_clienteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_contraseñaus, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        crear_clienteLayout.setVerticalGroup(
            crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_clienteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_idus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_primus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_segunus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_apeus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_segunape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jd_nacius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jd_afius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_contraseñaus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        jLabel14.setText("Id usuario:");

        jLabel15.setText("Primer nombre:");

        jLabel16.setText("Segundo nombre:");

        jLabel17.setText("Primer apellido:");

        jLabel18.setText("Fecha de nacimineto:");

        jLabel19.setText("Fecha de afiliacion:");

        jb_crearmantenimiento.setText("Crear usuario");
        jb_crearmantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearmantenimientoMouseClicked(evt);
            }
        });

        jLabel20.setText("Segundo apellido:");

        cb_elegiratm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_elegiratmItemStateChanged(evt);
            }
        });

        jLabel22.setText("Atm que puede reparar:");

        jLabel27.setText("Contraseña:");

        javax.swing.GroupLayout crear_mantenimientoLayout = new javax.swing.GroupLayout(crear_mantenimiento.getContentPane());
        crear_mantenimiento.getContentPane().setLayout(crear_mantenimientoLayout);
        crear_mantenimientoLayout.setHorizontalGroup(
            crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jb_crearmantenimiento))
                    .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel18)
                            .addGap(18, 18, 18)
                            .addComponent(jd_nacius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crear_mantenimientoLayout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_idus1))
                                .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_primus1))
                                .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_segunus1))
                                .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_apeus1))
                                .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                    .addComponent(jd_afius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_segunape1)))))
                    .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_contraseñaus1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(cb_elegiratm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        crear_mantenimientoLayout.setVerticalGroup(
            crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_mantenimientoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_idus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_primus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_segunus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_apeus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_segunape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jd_nacius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jd_afius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_elegiratm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_contraseñaus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_crearmantenimiento)
                .addContainerGap())
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setText("En que Atm deseas hacer tus acciones?");

        jb_aceptar.setText("Aceptar");
        jb_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_aceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout decidir_atmLayout = new javax.swing.GroupLayout(decidir_atm.getContentPane());
        decidir_atm.getContentPane().setLayout(decidir_atmLayout);
        decidir_atmLayout.setHorizontalGroup(
            decidir_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decidir_atmLayout.createSequentialGroup()
                .addGroup(decidir_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decidir_atmLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel21))
                    .addGroup(decidir_atmLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(cb_atms, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(decidir_atmLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jb_aceptar)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        decidir_atmLayout.setVerticalGroup(
            decidir_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decidir_atmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(36, 36, 36)
                .addComponent(cb_atms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jb_aceptar)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel23.setText("Como que usuario deseas entrar?");

        jButton3.setText("mantenimiento");

        jButton4.setText("cliente ");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout decidir_usuarioLayout = new javax.swing.GroupLayout(decidir_usuario.getContentPane());
        decidir_usuario.getContentPane().setLayout(decidir_usuarioLayout);
        decidir_usuarioLayout.setHorizontalGroup(
            decidir_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decidir_usuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(67, 67, 67))
            .addGroup(decidir_usuarioLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton3)
                .addGap(85, 85, 85)
                .addComponent(jButton4)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        decidir_usuarioLayout.setVerticalGroup(
            decidir_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decidir_usuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel23)
                .addGap(79, 79, 79)
                .addGroup(decidir_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jLabel24.setText("Id usuario:");

        jLabel25.setText("Contraseña:");

        jButton5.setText("ENTRAR");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout inicio_clienteLayout = new javax.swing.GroupLayout(inicio_cliente.getContentPane());
        inicio_cliente.getContentPane().setLayout(inicio_clienteLayout);
        inicio_clienteLayout.setHorizontalGroup(
            inicio_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicio_clienteLayout.createSequentialGroup()
                .addGroup(inicio_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicio_clienteLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(inicio_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(inicio_clienteLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inicio_clienteLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_usuario))))
                    .addGroup(inicio_clienteLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton5)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        inicio_clienteLayout.setVerticalGroup(
            inicio_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicio_clienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(inicio_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(inicio_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(pf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton5)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inicio_mantenimientoLayout = new javax.swing.GroupLayout(inicio_mantenimiento.getContentPane());
        inicio_mantenimiento.getContentPane().setLayout(inicio_mantenimientoLayout);
        inicio_mantenimientoLayout.setHorizontalGroup(
            inicio_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        inicio_mantenimientoLayout.setVerticalGroup(
            inicio_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout clienteLayout = new javax.swing.GroupLayout(cliente.getContentPane());
        cliente.getContentPane().setLayout(clienteLayout);
        clienteLayout.setHorizontalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        clienteLayout.setVerticalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mantenimientoLayout = new javax.swing.GroupLayout(mantenimiento.getContentPane());
        mantenimiento.getContentPane().setLayout(mantenimientoLayout);
        mantenimientoLayout.setHorizontalGroup(
            mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mantenimientoLayout.setVerticalGroup(
            mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienevenido al Banco Ficohsa");

        jb_crearatm.setText("Crear ATM");
        jb_crearatm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearatmMouseClicked(evt);
            }
        });

        jb_crearus.setText("Crear usuario");
        jb_crearus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearusMouseClicked(evt);
            }
        });

        jb_iniciosesion.setText("Iniciar sesion");
        jb_iniciosesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciosesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jb_crearatm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jb_crearus)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jb_iniciosesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_crearatm)
                    .addComponent(jb_crearus))
                .addGap(52, 52, 52)
                .addComponent(jb_iniciosesion)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        atms.add(new Atm(tf_ubic.getText(), Integer.parseInt(tf_idatm.getText()), jd_fabric.getDate(), tf_manetenimiento.getText()));
        JOptionPane.showMessageDialog(null, "ATM creado con exito");
        Crear_atm.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_crearatmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearatmMouseClicked
        // TODO add your handling code here:
        Crear_atm.pack();
        Crear_atm.setLocationRelativeTo(null);
        Crear_atm.setVisible(true);
    }//GEN-LAST:event_jb_crearatmMouseClicked

    private void jb_mantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_mantenimientoMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(atms.toArray());
        cb_elegiratm.setModel(modelo);
        
        decision_usuario.setVisible(false);
        crear_mantenimiento.pack();
        crear_mantenimiento.setLocationRelativeTo(null);
        crear_mantenimiento.setVisible(true);

    }//GEN-LAST:event_jb_mantenimientoMouseClicked

    private void jb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clienteMouseClicked
        // TODO add your handling code here:
        decision_usuario.setVisible(false);
        crear_cliente.pack();
        crear_cliente.setLocationRelativeTo(null);
        crear_cliente.setVisible(true);
    }//GEN-LAST:event_jb_clienteMouseClicked

    private void jb_crearusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearusMouseClicked
        // TODO add your handling code here:
        decision_usuario.pack();
        decision_usuario.setLocationRelativeTo(null);
        decision_usuario.setVisible(true);
    }//GEN-LAST:event_jb_crearusMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        client.add(new cliente(Integer.parseInt(tf_idus.getText()), tf_primus.getText(), tf_segunus.getText(), tf_apeus.getText(), tf_segunape.getText(), jd_nacius.getDate(), jd_afius.getDate(),tf_contraseñaus.getText()));
        JOptionPane.showMessageDialog(null, "Usuario creado con exito");
        crear_cliente.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_crearmantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearmantenimientoMouseClicked
        // TODO add your handling code here:
        Mantenimiento man;
        manten.add(man=new Mantenimiento(Integer.parseInt(tf_idus1.getText()), tf_primus1.getText(), tf_segunus1.getText(), tf_apeus1.getText(), tf_segunape1.getText(), jd_nacius1.getDate(), jd_afius1.getDate(),tf_contraseñaus1.getText()));
        Atm temp = (Atm) cb_elegiratm.getSelectedItem();
        if (temp != null) {
            man.getReparar().add(temp);
        }
        JOptionPane.showMessageDialog(null, "Usuario creado con exito");
        crear_mantenimiento.setVisible(false);
    }//GEN-LAST:event_jb_crearmantenimientoMouseClicked

    private void jb_iniciosesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciosesionMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(atms.toArray());
        cb_atms.setModel(modelo);
        decidir_atm.pack();
        decidir_atm.setLocationRelativeTo(null);
        decidir_atm.setVisible(true);

    }//GEN-LAST:event_jb_iniciosesionMouseClicked

    private void jb_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_aceptarMouseClicked
        // TODO add your handling code here:
        decidir_usuario.pack();
        decidir_usuario.setLocationRelativeTo(null);
        decidir_usuario.setVisible(true);
        decidir_atm.setVisible(false);
    }//GEN-LAST:event_jb_aceptarMouseClicked

    private void cb_elegiratmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_elegiratmItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_elegiratmItemStateChanged

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        inicio_cliente.pack();
        inicio_cliente.setLocationRelativeTo(null);
        inicio_cliente.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        for (cliente c : client) {
            if(c.getIdusuario()==Integer.parseInt(tf_usuario.getText())&&c.getContraseña().equals(pf_contraseña.getText())){
            cliente.pack();
            cliente.setLocationRelativeTo(null);
            cliente.setVisible(true);
            adminlog al=new adminlog("./Log.txt");
            al.cargarArchivo();
            Date d=new Date();
            al.setlog(new Log(c.getPrimnombre(),"Inicio sesion", d.toString()));
            inicio_cliente.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Crear_atm;
    private javax.swing.JComboBox<String> cb_atms;
    private javax.swing.JComboBox<String> cb_elegiratm;
    private javax.swing.JDialog cliente;
    private javax.swing.JDialog crear_cliente;
    private javax.swing.JDialog crear_mantenimiento;
    private javax.swing.JDialog decidir_atm;
    private javax.swing.JDialog decidir_usuario;
    private javax.swing.JDialog decision_usuario;
    private javax.swing.JDialog inicio_cliente;
    private javax.swing.JDialog inicio_mantenimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb_aceptar;
    private javax.swing.JButton jb_cliente;
    private javax.swing.JButton jb_crearatm;
    private javax.swing.JButton jb_crearmantenimiento;
    private javax.swing.JButton jb_crearus;
    private javax.swing.JButton jb_iniciosesion;
    private javax.swing.JButton jb_mantenimiento;
    private com.toedter.calendar.JDateChooser jd_afius;
    private com.toedter.calendar.JDateChooser jd_afius1;
    private com.toedter.calendar.JDateChooser jd_fabric;
    private com.toedter.calendar.JDateChooser jd_nacius;
    private com.toedter.calendar.JDateChooser jd_nacius1;
    private javax.swing.JDialog mantenimiento;
    private javax.swing.JPasswordField pf_contraseña;
    private javax.swing.JTextField tf_apeus;
    private javax.swing.JTextField tf_apeus1;
    private javax.swing.JTextField tf_contraseñaus;
    private javax.swing.JTextField tf_contraseñaus1;
    private javax.swing.JTextField tf_idatm;
    private javax.swing.JTextField tf_idus;
    private javax.swing.JTextField tf_idus1;
    private javax.swing.JTextField tf_manetenimiento;
    private javax.swing.JTextField tf_primus;
    private javax.swing.JTextField tf_primus1;
    private javax.swing.JTextField tf_segunape;
    private javax.swing.JTextField tf_segunape1;
    private javax.swing.JTextField tf_segunus;
    private javax.swing.JTextField tf_segunus1;
    private javax.swing.JTextField tf_ubic;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
